### ISSUE TITLE
問題.1 ステージが消えない

### ISSUE THREAD

**Issue by Ryohei0815** [Ryohei0815/criminalstars#1]
# 現状の問題

前回ステージが出現する機能は追加して、消える機能を追加できていません。
下記のように書いてみたんですが、消えません。
Destroy(groundPrefab)でも試してみたんですが、ダメでした。
エラーは出ていません。

最初のステージブロックのx座標が-38になった位置でに画面の外に出ます。

	[SerializeField] GameObject groundPrefab;
	[SerializeField] GameObject prevObj;

	void Update () {
		if (prevObj.transform.position.x < -10) {
			prevObj = Instantiate (groundPrefab, new Vector3(39, -4 , 0), Quaternion.identity) as GameObject;
		}

		if (prevObj.transform.position.x < -38) {
			Destroy (preObj);
		}

	}

**Comment by Ryohei0815** [comment]
# できました！！
ステージブロック自体に消えるスクリプトをつけたらいけました。

**Comment by ryosebach** [comment]
原因としてはprevObjはx<-10となると、新しいprevObjが生成されてx<-38とならないせいだねー
このスクリプトでやりたいなら、もう一つ変数を増やして
nextObjに生成したものを代入して、適宜更新すればいけるよー

**Comment by ryosebach** [comment]
@Ryohei0815 
具体的にはこんな感じで
```
	[SerializeField] GameObject groundPrefab;
	[SerializeField] GameObject prevObj;
        [SerializeField] GameObject nextObj;

	void Update () {
		if (nextObj.transform.position.x < -10) {
			nextObj = Instantiate (groundPrefab, new Vector3(39, -4 , 0), Quaternion.identity) as GameObject;
		}

		if (prevObj.transform.position.x < -38) {
			Destroy (preObj);
                        prevObj = nextObj;
		}

	}
```
