### ISSUE TITLE
問題.2 障害物をランダムな位置に追加

### ISSUE THREAD

**Issue by Ryohei0815** [Ryohei0815/criminalstars#2]
## 現状の問題

障害物をランダムな個数でランダムな位置に生成させたいです。
コードは下記のように書きましたが、画像のようにエラーが出ています。

numをランダムな数で指定し、指定された数になった時、ランダムな位置に生成させようとしています。

	public GameObject barrier;
	int num = Randam.Range(0,3);

	void Awake(){
		if (num = 0) {
			transform.position = new Vector3 (Randam.Range(14,62),0,0);
			Instantiate (barrier,transform.position,Quaternion.identity);
		}
		
	}

![2017-09-27 19 11 56](https://user-images.githubusercontent.com/27498762/30908257-034ed156-a3b8-11e7-8e8f-f2d1ac0d3e78.png)
![2017-09-27 19 13 01](https://user-images.githubusercontent.com/27498762/30908291-20ba7b96-a3b8-11e7-86fe-9ee75c3ddb50.png)

**Comment by ryosebach** [comment]
@Ryohei0815 

```hoge.cs
public GameObject barrier;
	int num = Randam.Range(0,3);


	void Awake(){
		if (num = 0) {
                //ここ num と 0 を比較するのじゃなくて 代入してしまってるよー
                // num == 0だね
			transform.position = new Vector3 (Randam.Range(14,62),0,0);
			Instantiate (barrier,transform.position,Quaternion.identity);
		}
		
	}
```

**Comment by ryosebach** [comment]
@Ryohei0815 
あとこれでは生成してもブロックは動かないと思うので， prevObjのこオブジェクトにするようにするといいかもしれない！（prevObjをGetComponentしたGroundManagerから参照しておいたうえで）

```
GameObject barrierObj = Instantiate (barrier, ~~~~~~~) as GameObject;
barrierObj.transform.parent = prevObj.transform;
```

**Comment by Ryohei0815** [comment]
prevObjをGetComponentしたGroundManagerから参照ってどうやるんでしょう...。
とりあえず書くだけ書いたんですが...。
	GameObject refObj;

	public GameObject barrierObj;
	int num = Random.Range(0,3);


	void Awake(){
		if (num == 0) {
			transform.position = new Vector3 (Random.Range(14f,62f),-2.25f,0);
			Instantiate (barrierObj,transform.position,Quaternion.identity);
		}
		
	}
	

	void Update () {

		GroundScript d1= refObj.GetComponent<GroundScript> ();
	}

**Comment by ryosebach** [comment]
@Ryohei0815 

- GetComponentは Updateの中で行わない
  + Awakeの中でGetComponentする
- GetComponentした参照をその後も利用するため，変数の宣言は最初に行う
  + 変数のスコープで調べるといいかも．何個か例を以下に
     - [参考1](http://gihyo.jp/dev/serial/01/code/000302)
     - [参考2](http://ufcpp.net/study/csharp/start/st_scope/)
- Awakeの中でInstantiateしない
  + これはその前のコメントで返せばよかったのだけれど，せめてStartで
  + そしてStartでも障害物の生成が一回しか行われないのでUpdateのなかで n秒 に一回の頻度で生成されるように

これで少し考えてみてほしい！わかんないって感じだったらすぐに聞いてきて！

**Comment by Ryohei0815** [comment]
**詳しくありがとうございます！**
参考1は「フィールド変数のスコープ」っていう部分がわかりづらいです。
参考2は例外1,2以降がわかりにくいです。
用語として、フィールド変数、ローカル変数、メンバーっていう言葉の意味がまだ理解できていないです。

作りたいものとしては、ステージが生成された時に同時にx座標がランダムな位置にランダムな数、障害物が生成されるようにしたいです。

**Comment by ryosebach** [comment]
@Ryohei0815 
プログラム中においては多数のブロックと呼ばれるものが存在していて

```hoge.cs
public class NewMonobehaviourScript : MonoBehaviour {
  void Start() {
    if(true) {
    }
  }
  void Update() {
  }
}
```
例えば上だと，class全体が一つのブロック．各関数 Start, Updateが一つのブロック，そしてif文の中身もまた一つのブロックとなっている．

そしてブロックは独立と内包のどちらかで存在することができる．
今回であれば，classのブロックの中に全てが含まれているので，classのブロックとその他のブロックは全て内包の関係にある．また各関数は独立の関係にもなっている．

ブロックの単位は `{` で始まって，それに対応する `}` で一つと思えば大丈夫．

そして，ブロックで宣言された変数は，そのブロックの中，またそのブロックが内包するブロックの中においては機能するが，宣言されたブロックの外からは呼び出すことができず機能しない．

なので，上のデップの

```.cs
public GameObject barrierObj;
int num = Random.Range(0,3);

void Awake(){
	if (num == 0) {
		transform.position = new Vector3 (Random.Range(14f,62f),-2.25f,0);
		Instantiate (barrierObj,transform.position,Quaternion.identity);
	}	
}
void Update () {
	GroundScript d1= refObj.GetComponent<GroundScript> ();
}
```
においては，Updateブロックの中で宣言された変数 d1 はそのブロックの中でしか利用できなくなってしまう．
今回であれば，ブロックを生成する時に，GroudScriptの変数である prevObjを参照したいため，参照する時にも d1 の変数にアクセスする必要がある．
そのため，一番大きなブロックである，クラスの変数として d1 は宣言すべきということ．

具体的には，
```.cs
public GameObject barrierObj;
int num = Random.Range(0,3);
GroundScript d1;

void Awake() {
  //この中でd1にGetComponentしたGroundScriptを代入する
}
```

とするべきだね．



---

伝わるかな？？

**Comment by Ryohei0815** [comment]
**すだちの助けもあり、わかりました！**
### 新たな問題
現在、生成された障害物のスケールが大変な事になってしまう問題が発生しています。
親子関係にあるオブジェクトの子になっているオブジェクトが生成される時、同じような問題が出るとネットには書いてありました。

現在、直そうとしていますが、一旦Githubに上げてあります。

また、すだちの助言より、障害物をランダムな数作る部分のやり方を変えてあります。

**Comment by ryosebach** [comment]
ちょっとまってね！
