### ISSUE TITLE
問題.5 手配度の表し方の問題

### ISSUE THREAD

**Issue by Ryohei0815** [Ryohei0815/criminalstars#5]
### やりたいこと

GTAの手配度のように、手配度があがると星の数が増えるようにしたいです。星の最大は６です。

手配度が少なければ、例えば手配度が「3」なら黄色い星（明るい星）、残り３つは黒い星（暗い星）に最大まで増えると、すべて黄色い星にしたいです。

★星が少ない時

![maxresdefault 1](https://user-images.githubusercontent.com/27498762/31311269-a1cef1ac-abe3-11e7-87f9-80b91c6326be.jpg)

★星が最大の時（これは五つですが）
![maxresdefault](https://user-images.githubusercontent.com/27498762/31311270-a5f7cf74-abe3-11e7-90a1-7ae6517a83db.jpg)

RendererのカラーをGetComponentして変えればいいかなと思ったんですが、星一つ一つを管理して、一つ一つGetComponentしなければならないのではと思ったので、よくないと思いました。

### 代替案

もし上記の機能がなかなか難しければ、ただ表示される星の数が変わるだけでも構いません。

また、時間がなければ、最悪、数字で表現してもいいと思っています。

**Comment by ryosebach** [comment]
まずは，手配度がGameManagerで管理されていると思うから，それを読み出して管理することになる

アイデアの方向としては何個かあって．
## 一つ目

黄色の星が6つ並んだ画像と, 黒い星が6つ並んだ画像を同じサイズで二つ用意して，
黒い星の上に黄色い星が重なるようにして配置，黄色い星の Image Typeを `Filled` にして，パーセントで表現できるようにする．現在の手配度 / 6fの値をfill amountに代入すればいい感じになると思う．

## 二つ目
丁寧に画像でやるのもありな気がする．これは追記

**Comment by ryosebach** [comment]
二つ目の話

```
public class StarController : MonoBehaviour {

	public Image[] starImages;
	public Color defaultColor;
	public Color highlightColor;

	void Awake() {
		starImages = GetComponentsInChildren<Image>();
	}

	void Update() {
		for (int i = 0; i < 6; i++) {
			if (i < GameManager.Instance.degree) {
				starImages[5 - i].color = highlightColor;
			} else {
				starImages[5 - i].color = defaultColor;
			}
		}
	}

}
```
みたいなスクリプトを

![2017-10-09 1 27 17](https://user-images.githubusercontent.com/15684002/31318672-0721827e-ac91-11e7-88ce-8c559f4bdd53.png)

こんな感じにした Stars (空のゲームオブジェクトに名前つけただけ) につければいい感じに動くよー

**Comment by ryosebach** [comment]
どちらにせよ，丁寧にスクリプトを書くことには変わりはないかも．
Unityの機能を使うと選択肢1, スクリプトで動かすなら選択肢2ってところかな

**Comment by ryosebach** [comment]
![stars](https://user-images.githubusercontent.com/15684002/31318717-766ee4be-ac91-11e7-907d-3ef3d97a73b8.gif)
二つ目の方はこんなかこんな感じになる
一つ目は試してないけど，うまくいくとは思う
